In [54]:
import pandas as pd

pd.set_option('display.max_columns', 30)

# 1.读取数据
data = pd.read_csv('data/sales.csv')


# 2.数据清洗
# 2.1缺失值处理
data.isnull()   # 查看缺失值
# 2.1.1 删除缺失值
data.dropna()   # 删除缺失值所在行
data.dropna(axis=1)  # 删除缺失值所在列

# 2.1.2填充缺失值
data.fillna(0)  # 填充0
data.ffill()  # 填充上一行数据
data.bfill()  # 填充下一行数据

            订单号  产品类别    产品名称  销售数量    单价   销售金额
0    6805677496  家居用品      枕头  10.0   199   1990
1    5857234132    食品      海苔   5.0    29    145
2    5888085059  电子产品    智能音箱   3.0   399   1995
3    6823473137    食品      面包   3.0    29     87
4    6801664364    食品      薯片   2.0    19     38
5    5897064217    图书      字帖   4.0    29    116
6    6857752388    服装      袜子   7.0   -29   -203
7    6898807429    服装      T恤   6.0   199   1194
8    5875402232  电子产品     路由器   9.0   299   2691
9    5888085059    图书      字典   2.0    99    198
10   5808071569    食品     矿泉水   9.0    29    261
11   6890234923  家居用品    餐具套装  10.0   199   1990
12   5891597362  电子产品      鼠标   3.0    89    267
13   6880065056    图书     练习册   8.0    39    312
14   5804178086  电子产品    蓝牙耳机  10.0   199   1990
15   5878551159    图书     练习册   5.0    39    195
16   5812573980    食品      坚果   2.0    79    158
17   5835623429    图书      食谱   6.0    49    294
18   5852698441  家居用品      蜡烛   6.0    49    294
19   5852807025    服装      毛衣  10.0   399   3990
20   6893087111    食品      蜂蜜  10.0    89    890
21   5871374068    图书     摄影集   5.0   129    645
22   5894724625  电子产品    智能手机   9.0  2999  26991
23   6867258691    服装      围巾   8.0   129   1032
24   5875023454  电子产品    智能手机   8.0  2999  23992
25   6837065480    服装      毛衣   3.0   399   1197
26   5854211330    食品      果干   9.0    59    531
27   5840958148    服装      衬衫   6.0   299   1794
28   6842052369  家居用品      扫把   1.0    39     39
29   5816896128    食品      咖啡   4.0   129    516
30   6821256262    图书      食谱   6.0    49    294
31   5837205437    服装      短裤   2.0   149    298
32   6816687256    服装     运动裤   7.0   249   1743
33   6867240278    服装      短裤   8.0   149   1192
34   6859288203  电子产品     钢化膜   2.0    39     78
35   5815847468  电子产品     显示器   5.0  1299   6495
36   6870668206  家居用品      拖把   6.0    89    534
37   6871778377    食品      薯片   2.0    19     38
38   6896363474    图书     练习册   7.0    39    273
39   6857955578    图书     科普书   5.0    59    295
40   5864587553    服装      袜子   8.0    29    232
41   6861733608  家居用品      衣架   2.0    39     78
42   5848602769    食品     能量棒   1.0    49     49
43   6896687125    食品      果汁   2.0    39     78
44   5809051775  电子产品      鼠标   9.0    89    801
45   5828073333  家居用品      水杯   2.0    49     98
46   5820473594    服装     运动裤   7.0   249   1743
47   5823379341  电子产品   笔记本电脑   1.0  5999   5999
48   5835099410    图书    技术书籍   4.0    89    356
49   6842655345    食品      蜂蜜   7.0    89    623
50   6872501498  家居用品      衣架   4.0    39    156
51   6803742747  电子产品     麦克风   2.0   299    598
52   5835714436    服装      围巾   2.0   129    258
53   6807804795  电子产品     钢化膜   9.0    39    351
54   6872340030  家居用品      衣架   5.0    39    195
55   6840254213    食品     矿泉水  10.0    29    290
56   5870793859    食品      饼干   6.0    39    234
57   5876880041    服装     运动裤   2.0   249    498
58   6885078432  家居用品      沙发   7.0  3999  27993
59   5805524413    食品      牛奶   5.0    69    345
60   6802066319    服装      睡衣   4.0   199    796
61   5876009437    食品      肉脯   7.0    69    483
62   6857386517    食品      海苔   4.0    29    116
63   6893849823  电子产品      键盘   3.0   199    597
64   6818686763  家居用品    餐具套装   6.0   199   1194
65   6818771197    服装     羽绒服   4.0   899   3596
66   6803345146  电子产品    智能音箱  10.0   399   3990
67   6857671635  电子产品     手机壳   1.0    49     49
68   6888558142    服装      手套   5.0    59    295
69   5802859418  家居用品     洗衣液   2.0    49     98
70   5857892499    食品     巧克力   6.0    59    354
71   6881307037    服装      外套   6.0   599   3594
72   6882472708    食品   零食大礼包   5.0    89    445
73   6896836654  家居用品      窗帘   1.0   399    399
74   6807517971  电子产品    无线耳机   1.0   299    299
75   6868450800    图书      绘本   9.0    59    531
76   5835168341    服装      围巾   5.0   129    645
77   6862213600  电子产品     手机壳   9.0    49    441
78   5817942253  家居用品      毛巾   9.0    49    441
79   6838419156    服装      T恤   1.0   199    199
80   6832672046    服装      卫衣   2.0   349    698
81   6882641183    食品      坚果   1.0    79     79
82   5882040279    图书     练习册   3.0    39    117
83   5856960206    食品     能量棒   3.0    49    147
84   6835930946    服装     休闲裤   2.0   299    598
85   6884401422    图书     笔记本   9.0    49    441
86   6817646898  家居用品      衣架   8.0    39    312
87   5824138220    图书      日历   3.0    39    117
88   5810483850  家居用品      床垫   5.0  5999  29995
89   6874228092  电子产品    无线耳机   1.0   299    299
90   5825937662  电子产品     钢化膜   6.0    39    234
91   6899540878  家居用品      床垫   4.0  5999  23996
92   6815202927  家居用品      地毯   8.0   299   2392
93   5803850839  电子产品      键盘   6.0   199   1194
94   6850947020  家居用品      纸巾   5.0    39    195
95   5840069589    图书      画册   3.0    99    297
96   6882159173    食品      蜂蜜   7.0    89    623
97   6847661479    食品      薯片   8.0    19    152
98   5848428039    食品      茶叶  10.0   199   1990
99   6868231493    食品      薯片   5.0    19     95
100  5832758970    服装      风衣   8.0   699   5592
101  6899145716    图书      杂志   8.0    29    232
102  6893625569    服装      围巾   8.0   129   1032
103  5863393961  电子产品    游戏手柄   2.0   249    498
104  6827358966    图书      字典   6.0    99    594
105  5878543628  家居用品     洗洁精  10.0    29    290
106  5824298537    服装      卫衣   8.0   349   2792
107  6868959743    图书     笔记本   4.0    49    196
108  6826045080    服装      睡衣   3.0   199    597
109  5855176585    图书     科普书   5.0    59    295
110  6856521224    服装      风衣   6.0   699   4194
111  5838735887    图书      画册   7.0    99    693
112  5863809863  家居用品     垃圾桶   2.0    59    118
113  5818261249    食品      茶叶   6.0   199   1194
114  5845257567    图书      绘本   9.0    59    531
115  6876712100  家居用品      衣架   1.0    39     39
116  5854511595    食品   零食大礼包   2.0    89    178
117  5894610701  家居用品      拖把   2.0    89    178
118  6865301539    食品   零食大礼包   4.0    89    356
119  5862128107  家居用品      沙发   3.0  3999  11997
120  6885746519  电子产品    游戏手柄   4.0   249    996
121  6892321515    食品      坚果  10.0    79    790
122  5883797573    食品      麦片   7.0    49    343
123  5818113431  家居用品      床垫   8.0  5999  47992
124  6883278187  家居用品     垃圾桶   1.0    59     59
125  6818053882    食品      牛奶   4.0    69    276
126  5891955361  电子产品     钢化膜   5.0    39    195
127  5883983174  家居用品      窗帘  10.0   399   3990
128  5866054840    图书      字典  10.0    99    990
129  5821394002  家居用品     收纳盒   1.0    79     79
130  5839652877    图书      漫画   5.0    39    195
131  5866179578  电子产品   笔记本电脑   2.0  5999  11998
132  6860644623  电子产品     存储卡   1.0   129    129
133  5817207922    服装     连衣裙   7.0   499   3493
134  6826538206  电子产品     麦克风   7.0   299   2093
135  6861726538  家居用品      地毯  10.0   299   2990
136  6873808416  家居用品      沙发   8.0  3999  31992
137  5813233987    食品     方便面   5.0    49    245
138  5853556066  家居用品      纸巾   8.0    39    312
139  6879411860  家居用品      沙发   6.0  3999  23994
140  5831376701    食品      薯片   2.0    19     38
141  5879174422    图书     散文集   6.0    59    354
142  5823360689  电子产品    智能手机   7.0  2999  20993
143  5883051305  电子产品    智能手机  10.0  2999  29990
144  6832294234    食品      咖啡   2.0   129    258
145  6871931711  家居用品      衣架  10.0    39    390
146  6856378469    服装     半身裙   8.0   299   2392
147  5800194073    服装      毛衣   6.0   399   2394
148  5800449605  家居用品     洗洁精   8.0    29    232
149  5846265329  家居用品      床垫   3.0  5999  17997
150  5867938109  电子产品      键盘   2.0   199    398
151  5893341133    食品      糖果   7.0    39    273
152  6875304597    食品     能量棒   8.0    49    392
153  6835056691    服装      袜子   3.0    29     87
154  5854493676    服装     牛仔裤   2.0   399    798
155  6862563518    服装     西装裤   7.0   449   3143
156  6811607405    食品      饼干   6.0    39    234
157  6869448173    食品     巧克力   3.0    59    177
158  5848997046    图书     散文集   8.0    59    472
159  5811798968    服装      内衣   5.0    89    445
160  6821795644    食品      咖啡   8.0   129   1032
161  5864529489    图书    旅游指南   2.0    69    138
162  6855377041    图书      日历   5.0    39    195
163  5830456448  家居用品      窗帘   3.0   399   1197
164  6871381333  电子产品     路由器   4.0   299   1196
165  6888789224    服装      手套   7.0    59    413
166  5801646266    食品   零食大礼包   4.0    89    356
167  5874099485  家居用品      香薰   7.0    99    693
168  5843813257  家居用品      沙发   1.0  3999   3999
169  5843474151    服装     西装裤   1.0   449    449
170  5819162283  家居用品      窗帘   2.0   399    798
171  5879241383    图书     摄影集   5.0   129    645
172  6890353450    食品     方便面   5.0    49    245
173  6865052496    服装     半身裙   8.0   299   2392
174  6805321631    服装      外套   1.0   599    599
175  5805146346    食品      咖啡   5.0   129    645
176  6873127248  家居用品      地毯   8.0   299   2392
177  6844904388  家居用品     收纳盒  10.0    79    790
178  6836585103  电子产品  USB数据线   9.0    29    261
179  5821778573    服装      衬衫   7.0   299   2093
180  6805779311    服装     运动裤   8.0   249   1992
181  5801873309  电子产品     路由器   7.0   299   2093
182  6842433686  电子产品      U盘   1.0    59     59
183  5827508455  家居用品      蜡烛   5.0    49    245
184  6855956978  家居用品      蜡烛   2.0    49     98
185  6817708051  家居用品      蜡烛   5.0    49    245
186  5837602170    图书      字帖   8.0    29    232
187  6816376743  电子产品  USB数据线   2.0    29     58
188  5816285494    食品      牛奶   1.0    69     69
189  6878949527  电子产品    无线耳机   3.0   299    897
190  5867072555    服装     西装裤   2.0   449    898
191  5876638261    服装      袜子   5.0    29    145
192  5874746458    服装     西装裤   1.0   449    449
193  6859826757    图书      画册   2.0    99    198
194  6855967378    图书      字帖   6.0    29    174
195  6812374694    服装      毛衣   9.0   399   3591
196  5847458425  家居用品      桌布   9.0    79    711
197  6826667587    服装     连衣裙   5.0   499   2495
198  5823039491    图书     练习册   2.0    39     78
199  6844981163    食品      茶叶   2.0   199    398
200  6852976345  电子产品     手机壳   5.0    49    245
201  5814938951  电子产品    平板电脑  10.0  2499  24990
202  5828470938    服装      短裤   2.0   149    298
203  6835026769    图书      诗集   2.0    49     98
204  6890609921  电子产品   笔记本电脑  10.0  5999  59990
205  6869333277  家居用品      床垫   9.0  5999  53991
206  6873254331  家居用品      窗帘   1.0   399    399
207  5881589365  家居用品      枕头   1.0   199    199
208  5822667696    图书     摄影集   8.0   129   1032
209  5852286595  电子产品     手机壳   6.0    49    294
210  5868514156    食品      果干  10.0    59    590
211  6850815278  家居用品      枕头   6.0   199   1194
212  6824315481  家居用品      衣架   8.0    39    312
213  6845880542    食品      海苔  10.0    29    290
214  6811136677  电子产品     显示器   5.0  1299   6495
215  5811267840    服装      短裤   8.0   149   1192
216  6874679301    服装     休闲裤   5.0   299   1495
217  6825956707  家居用品      毛巾   5.0    49    245
218  6879211098    图书     练习册  10.0    39    390
219  6883194186    食品      肉脯  10.0    69    690
220  5853054830    食品      肉脯   1.0    69     69
221  5805170374  家居用品      水杯   8.0    49    392
222  5863073750    食品      海苔   6.0    29    174
223  6879242690    食品   零食大礼包   3.0    89    267
224  5891062479    食品      饼干  10.0    39    390
225  6872729357    服装      短裤   4.0   149    596
226  5889283753  电子产品    智能音箱   5.0   399   1995
227  5814567651  家居用品      毛巾   6.0    49    294
228  5885541001  家居用品    餐具套装   6.0   199   1194
229  6824310511  家居用品      枕头   6.0   199   1194
230  5878969657  家居用品      床垫   8.0  5999  47992
231  5853861556  电子产品     钢化膜   5.0    39    195
232  5827118463    食品      面包  10.0    29    290
233  5884726526  家居用品     收纳盒   1.0    79     79
234  6841626372  家居用品      沙发   2.0  3999   7998
235  6824834965    食品      坚果  10.0    79    790
236  5864200262  家居用品      床垫   4.0  5999  23996
237  6823999604    图书    旅游指南  10.0    69    690
238  6813380522  电子产品    智能手机   3.0  2999   8997
239  5854306954  家居用品      毛巾   6.0    49    294
240  5876354209    图书     笔记本   5.0    49    245
241  6804390223    食品      糖果   6.0    39    234
242  5825538313  电子产品     钢化膜   1.0    39     39
243  5887227925  电子产品    平板电脑   2.0  2499   4998
244  5893361218    图书     笔记本   3.0    49    147
245  5818152363  电子产品    蓝牙耳机   8.0   199   1592
246  6858035154    食品     方便面  10.0    49    490
247  6889194588    食品     巧克力   5.0    59    295
248  6833067503  家居用品      纸巾   5.0    39    195
249  6882063897    食品     巧克力   4.0    59    236
250  5814816711  家居用品      蜡烛   8.0    49    392
251  6815487266    图书    技术书籍   5.0    89    445
252  5841352622  家居用品      拖把   1.0    89     89
253  5841427707    食品      蜂蜜   7.0    89    623
254  5805792947  家居用品      扫把   4.0    39    156
255  6874166656    食品      麦片   2.0    49     98
256  6888548139    食品     能量棒   7.0    49    343
257  6867654283  电子产品    无线耳机   2.0   299    598
258  6837893528  家居用品      扫把   4.0    39    156
259  6890392173    食品      茶叶   5.0   199    995
260  6853663987    食品   零食大礼包   2.0    89    178
261  6802052554    服装      睡衣   3.0   199    597
262  5822424851    食品      坚果   4.0    79    316
263  6838941887  电子产品     路由器   7.0   299   2093
264  5851089960  家居用品      毛巾  10.0    49    490
265  5823329114    图书      字典   7.0    99    693
266  5821040515  电子产品     钢化膜   9.0    39    351
267  6830515225    图书     摄影集   7.0   129    903
268  6822412203    服装     休闲裤   8.0   299   2392
269  5817231648    服装      衬衫   5.0   299   1495
270  6841473447    食品      果汁   4.0    39    156
271  5815401663  家居用品      沙发   9.0  3999  35991
272  6832245129    食品     矿泉水  10.0    29    290
273  5884006836    食品      海苔   6.0    29    174
274  6808702911  电子产品     路由器   4.0   299   1196
275  5836984659    图书      食谱   7.0    49    343
276  5878122717  电子产品    智能手表  10.0   899   8990
277  6890876412    食品      海苔   1.0    29     29
278  6824270558    食品      薯片   1.0    19     19
279  6814064009    图书     练习册   9.0    39    351
280  5832052306  家居用品      毛巾   2.0    49     98
281  5865217126  电子产品     存储卡   7.0   129    903
282  6813149131  电子产品     手机壳   9.0    49    441
283  5865254576    食品     方便面   2.0    49     98
284  5864343049    服装      风衣   1.0   699    699
285  6824634614    服装     西装裤   2.0   449    898
286  5872729055  电子产品      键盘   2.0   199    398
287  6818532821    图书      漫画   8.0    39    312
288  6820986832    食品      肉脯   3.0    69    207
289  6899877847  家居用品      枕头  10.0   199   1990
290  6886260421  电子产品    移动电源   4.0   149    596
291  6860752624    图书      字帖   7.0    29    203
292  5877457110    食品      蜂蜜   2.0    89    178
293  5832560118    食品      薯片   7.0    19    133
294  5880846456    服装     西装裤   9.0   449   4041
295  5875231157    图书     笔记本   6.0    49    294
296  5873373109  家居用品     洗衣液   2.0    49     98
297  6871646723    图书      杂志   7.0    29    203
298  6829733993  家居用品      窗帘   7.0   399   2793
299  6889261873    图书     笔记本   8.0    49    392
300  6869253277    食品     方便面   1.0    49     49
301  6807376898  家居用品      香薰   7.0    99    693
302  6869886459    图书      教材   3.0    79    237
303  6806160339    食品   零食大礼包   3.0    89    267
304  6862175114    食品      面包   8.0    29    232
305  6827231926    图书      字典   4.0    99    396
306  5826822786  家居用品      地毯   2.0   299    598
307  6807847191    图书      漫画   8.0    39    312
308  5854096632    服装     牛仔裤   4.0   399   1596
309  6838020550  家居用品      地毯   5.0   299   1495
310  5838148763  电子产品    蓝牙耳机  10.0   199   1990
311  5855677494    食品      坚果  10.0    79    790
312  6812559570  电子产品    智能手表   9.0   899   8091
313  6833144246    食品     能量棒   5.0    49    245
314  6889158121    食品      牛奶  10.0    69    690
315  5881823286    图书      画册   5.0    99    495
316  6801495528    图书     历史书   9.0    89    801
317  6867566121    图书    旅游指南   6.0    69    414
318  6817604870    服装      围巾   5.0   129    645
319  6827897151    食品     能量棒   9.0    49    441
320  5830696359    食品      坚果   3.0    79    237
321  6840828332  家居用品     洗衣液   7.0    49    343
322  5857696039  电子产品    蓝牙耳机   8.0   199   1592
323  5859034879    服装     连衣裙   9.0   499   4491
324  5849308732    服装      风衣   5.0   699   3495
325  6809660384    食品     矿泉水   5.0    29    145
326  6803745732  家居用品     垃圾桶   8.0    59    472
327  5876386922    图书      漫画   6.0    39    234
328  5872884276    图书      食谱   5.0    49    245
329  6862898039    图书      字帖   9.0    29    261
330  6887906700  电子产品    移动电源   7.0   149   1043
331  5822235365  家居用品     垃圾桶   9.0    59    531
332  6836140342    食品   零食大礼包   1.0    89     89
333  6866915478    图书      绘本   2.0    59    118
334  5872942373    食品      饼干   8.0    39    312
335  6851028631    图书      字帖   1.0    29     29
336  6869653239    食品      糖果   6.0    39    234
337  5801962133  家居用品     收纳盒   2.0    79    158
338  6832952335    食品      果干   4.0    59    236
339  6840926430    图书     摄影集  10.0   129   1290
340  5834735575    食品      酸奶   5.0    59    295
341  6876402501    服装      睡衣  10.0   199   1990
342  6851411201    图书      字典   3.0    99    297
343  5825644770  家居用品     垃圾桶   2.0    59    118
344  6884360308  电子产品   笔记本电脑   5.0  5999  29995
345  6858821045  家居用品      沙发   8.0  3999  31992
346  6878999122  家居用品      香薰   3.0    99    297
347  5884742846    食品     巧克力   2.0    59    118
348  6873035797  电子产品     路由器   2.0   299    598
349  5871133274  电子产品      鼠标   1.0    89     89
350  5839574954  家居用品      地毯   4.0   299   1196
351  5878252086    食品      肉脯   7.0    69    483
352  6826816957    服装      手套   5.0    59    295
353  5881472337  家居用品      桌布   4.0    79    316
354  5831710697  家居用品    餐具套装   6.0   199   1194
355  6818372908    服装      风衣   1.0   699    699
356  6890163345    食品     矿泉水   9.0    29    261
357  5866711381    食品      肉脯  10.0    69    690
358  6874405722    食品      果汁   6.0    39    234
359  6862347895  电子产品      U盘  10.0    59    590
360  6862143082    图书     散文集  10.0    59    590
361  6881174739  家居用品      水杯   3.0    49    147
362  5890937948  电子产品  USB数据线   1.0    29     29
363  6859092130  家居用品      床垫   4.0  5999  23996
364  6864610136  电子产品    平板电脑   9.0  2499  22491
365  6856858615  电子产品    智能手机   5.0  2999  14995
366  6874044470    图书      字典   6.0    99    594
367  6811229309  家居用品      拖把   2.0    89    178
368  5867096000  电子产品    移动电源   3.0   149    447
369  5869692650  电子产品    移动电源   7.0   149   1043
370  5861400879    服装      卫衣   7.0   349   2443
371  5827294885  电子产品    移动电源   2.0   149    298
372  6878930826  电子产品  USB数据线   1.0    29     29
373  6894030876    图书      绘本   9.0    59    531
374  5866314665  电子产品     手机壳   9.0    49    441
375  5844313707    服装      短裤   3.0   149    447
376  5898273477  家居用品      毛巾   3.0    49    147
377  5878946554    服装      手套   6.0    59    354
378  5838636156    食品      蜂蜜   4.0    89    356
379  5852580673    食品      坚果   1.0    79     79
380  6891639233    食品      蜂蜜   6.0    89    534
381  6841710658  电子产品    无线耳机   9.0   299   2691
382  5844830398    食品      茶叶   9.0   199   1791
383  5813870384  电子产品    智能手表   3.0   899   2697
384  5800257671    图书    旅游指南   2.0    69    138
385  6868880875  家居用品      被子   9.0   399   3591
386  6835453724    图书     科普书   3.0    59    177
387  6837647011    服装      卫衣  10.0   349   3490
388  6873163407    图书     摄影集   7.0   129    903
389  5804112603  家居用品      沙发   2.0  3999   7998
390  6849785580  电子产品   笔记本电脑  10.0  5999  59990
391  5869835128  电子产品     手机壳   9.0    49    441
392  6802890262    图书      小说   9.0    49    441
393  5867475720    服装      卫衣   9.0   349   3141
394  5868828994    图书      字典   7.0    99    693
395  6898045661    图书     历史书   3.0    89    267
396  6865928279  电子产品     显示器   4.0  1299   5196
397  5831333751  电子产品    平板电脑   9.0  2499  22491
398  6845600235    食品     矿泉水   8.0    29    232
399  6860434598    图书      诗集   3.0    49    147
400  5863886364    服装      内衣   1.0    89     89
401  5803917597  家居用品      地毯   9.0   299   2691
402  6886426092    图书    技术书籍   7.0    89    623
403  6859888529    食品      咖啡   5.0   129    645
404  6895298343  电子产品    智能手机   9.0  2999  26991
405  6826516262  家居用品      蜡烛   6.0    49    294
406  6817711302  家居用品      枕头   6.0   199   1194

In [58]:
#2.2 重复值处理
#2.2.1 查看重复值
data.duplicated()
data.duplicated(subset=['订单号'])
# #2.2.2 删除重复值
data.drop_duplicates(subset=['订单号'], keep = 'last')   # keep = 'last' 保留最后出现的重复值 keep = 'first' 保留首次出现的重复值

            订单号  产品类别    产品名称  销售数量    单价   销售金额
0    6805677496  家居用品      枕头  10.0   199   1990
1    5857234132    食品      海苔   5.0    29    145
3    6823473137    食品      面包   3.0    29     87
4    6801664364    食品      薯片   2.0    19     38
5    5897064217    图书      字帖   4.0    29    116
6    6857752388    服装      袜子   7.0   -29   -203
7    6898807429    服装      T恤   6.0   199   1194
8    5875402232  电子产品     路由器   9.0   299   2691
9    5888085059    图书      字典   2.0    99    198
10   5808071569    食品     矿泉水   9.0    29    261
11   6890234923  家居用品    餐具套装  10.0   199   1990
12   5891597362  电子产品      鼠标   3.0    89    267
13   6880065056    图书     练习册   8.0    39    312
14   5804178086  电子产品    蓝牙耳机  10.0   199   1990
15   5878551159    图书     练习册   5.0    39    195
16   5812573980    食品      坚果   2.0    79    158
17   5835623429    图书      食谱   6.0    49    294
18   5852698441  家居用品      蜡烛   6.0    49    294
19   5852807025    服装      毛衣  10.0   399   3990
20   6893087111    食品      蜂蜜  10.0    89    890
21   5871374068    图书     摄影集   5.0   129    645
22   5894724625  电子产品    智能手机   9.0  2999  26991
23   6867258691    服装      围巾   8.0   129   1032
24   5875023454  电子产品    智能手机   8.0  2999  23992
25   6837065480    服装      毛衣   3.0   399   1197
26   5854211330    食品      果干   9.0    59    531
27   5840958148    服装      衬衫   6.0   299   1794
28   6842052369  家居用品      扫把   1.0    39     39
29   5816896128    食品      咖啡   4.0   129    516
30   6821256262    图书      食谱   6.0    49    294
31   5837205437    服装      短裤   2.0   149    298
32   6816687256    服装     运动裤   7.0   249   1743
33   6867240278    服装      短裤   8.0   149   1192
34   6859288203  电子产品     钢化膜   2.0    39     78
35   5815847468  电子产品     显示器   5.0  1299   6495
36   6870668206  家居用品      拖把   6.0    89    534
37   6871778377    食品      薯片   2.0    19     38
38   6896363474    图书     练习册   7.0    39    273
39   6857955578    图书     科普书   5.0    59    295
40   5864587553    服装      袜子   8.0    29    232
41   6861733608  家居用品      衣架   2.0    39     78
42   5848602769    食品     能量棒   1.0    49     49
43   6896687125    食品      果汁   2.0    39     78
44   5809051775  电子产品      鼠标   9.0    89    801
45   5828073333  家居用品      水杯   2.0    49     98
46   5820473594    服装     运动裤   7.0   249   1743
47   5823379341  电子产品   笔记本电脑   1.0  5999   5999
48   5835099410    图书    技术书籍   4.0    89    356
49   6842655345    食品      蜂蜜   7.0    89    623
50   6872501498  家居用品      衣架   4.0    39    156
51   6803742747  电子产品     麦克风   2.0   299    598
52   5835714436    服装      围巾   2.0   129    258
53   6807804795  电子产品     钢化膜   9.0    39    351
54   6872340030  家居用品      衣架   5.0    39    195
55   6840254213    食品     矿泉水  10.0    29    290
56   5870793859    食品      饼干   6.0    39    234
57   5876880041    服装     运动裤   2.0   249    498
58   6885078432  家居用品      沙发   7.0  3999  27993
59   5805524413    食品      牛奶   5.0    69    345
60   6802066319    服装      睡衣   4.0   199    796
61   5876009437    食品      肉脯   7.0    69    483
62   6857386517    食品      海苔   4.0    29    116
63   6893849823  电子产品      键盘   3.0   199    597
64   6818686763  家居用品    餐具套装   6.0   199   1194
65   6818771197    服装     羽绒服   4.0   899   3596
66   6803345146  电子产品    智能音箱  10.0   399   3990
67   6857671635  电子产品     手机壳   1.0    49     49
68   6888558142    服装      手套   5.0    59    295
69   5802859418  家居用品     洗衣液   2.0    49     98
70   5857892499    食品     巧克力   6.0    59    354
71   6881307037    服装      外套   6.0   599   3594
72   6882472708    食品   零食大礼包   5.0    89    445
73   6896836654  家居用品      窗帘   1.0   399    399
74   6807517971  电子产品    无线耳机   1.0   299    299
75   6868450800    图书      绘本   9.0    59    531
76   5835168341    服装      围巾   5.0   129    645
77   6862213600  电子产品     手机壳   9.0    49    441
78   5817942253  家居用品      毛巾   9.0    49    441
79   6838419156    服装      T恤   1.0   199    199
80   6832672046    服装      卫衣   2.0   349    698
81   6882641183    食品      坚果   1.0    79     79
82   5882040279    图书     练习册   3.0    39    117
83   5856960206    食品     能量棒   3.0    49    147
84   6835930946    服装     休闲裤   2.0   299    598
85   6884401422    图书     笔记本   9.0    49    441
86   6817646898  家居用品      衣架   8.0    39    312
87   5824138220    图书      日历   3.0    39    117
88   5810483850  家居用品      床垫   5.0  5999  29995
89   6874228092  电子产品    无线耳机   1.0   299    299
90   5825937662  电子产品     钢化膜   6.0    39    234
91   6899540878  家居用品      床垫   4.0  5999  23996
92   6815202927  家居用品      地毯   8.0   299   2392
93   5803850839  电子产品      键盘   6.0   199   1194
94   6850947020  家居用品      纸巾   5.0    39    195
95   5840069589    图书      画册   3.0    99    297
96   6882159173    食品      蜂蜜   7.0    89    623
97   6847661479    食品      薯片   8.0    19    152
98   5848428039    食品      茶叶  10.0   199   1990
99   6868231493    食品      薯片   5.0    19     95
100  5832758970    服装      风衣   8.0   699   5592
101  6899145716    图书      杂志   8.0    29    232
102  6893625569    服装      围巾   8.0   129   1032
103  5863393961  电子产品    游戏手柄   2.0   249    498
104  6827358966    图书      字典   6.0    99    594
105  5878543628  家居用品     洗洁精  10.0    29    290
106  5824298537    服装      卫衣   8.0   349   2792
107  6868959743    图书     笔记本   4.0    49    196
108  6826045080    服装      睡衣   3.0   199    597
109  5855176585    图书     科普书   5.0    59    295
110  6856521224    服装      风衣   6.0   699   4194
111  5838735887    图书      画册   7.0    99    693
112  5863809863  家居用品     垃圾桶   2.0    59    118
113  5818261249    食品      茶叶   6.0   199   1194
114  5845257567    图书      绘本   9.0    59    531
115  6876712100  家居用品      衣架   1.0    39     39
116  5854511595    食品   零食大礼包   2.0    89    178
117  5894610701  家居用品      拖把   2.0    89    178
118  6865301539    食品   零食大礼包   4.0    89    356
119  5862128107  家居用品      沙发   3.0  3999  11997
120  6885746519  电子产品    游戏手柄   4.0   249    996
121  6892321515    食品      坚果  10.0    79    790
122  5883797573    食品      麦片   7.0    49    343
123  5818113431  家居用品      床垫   8.0  5999  47992
124  6883278187  家居用品     垃圾桶   1.0    59     59
125  6818053882    食品      牛奶   4.0    69    276
126  5891955361  电子产品     钢化膜   5.0    39    195
127  5883983174  家居用品      窗帘  10.0   399   3990
128  5866054840    图书      字典  10.0    99    990
129  5821394002  家居用品     收纳盒   1.0    79     79
130  5839652877    图书      漫画   5.0    39    195
131  5866179578  电子产品   笔记本电脑   2.0  5999  11998
132  6860644623  电子产品     存储卡   1.0   129    129
133  5817207922    服装     连衣裙   7.0   499   3493
134  6826538206  电子产品     麦克风   7.0   299   2093
135  6861726538  家居用品      地毯  10.0   299   2990
136  6873808416  家居用品      沙发   8.0  3999  31992
137  5813233987    食品     方便面   5.0    49    245
138  5853556066  家居用品      纸巾   8.0    39    312
139  6879411860  家居用品      沙发   6.0  3999  23994
140  5831376701    食品      薯片   2.0    19     38
141  5879174422    图书     散文集   6.0    59    354
142  5823360689  电子产品    智能手机   7.0  2999  20993
143  5883051305  电子产品    智能手机  10.0  2999  29990
144  6832294234    食品      咖啡   2.0   129    258
145  6871931711  家居用品      衣架  10.0    39    390
146  6856378469    服装     半身裙   8.0   299   2392
147  5800194073    服装      毛衣   6.0   399   2394
148  5800449605  家居用品     洗洁精   8.0    29    232
149  5846265329  家居用品      床垫   3.0  5999  17997
150  5867938109  电子产品      键盘   2.0   199    398
151  5893341133    食品      糖果   7.0    39    273
152  6875304597    食品     能量棒   8.0    49    392
153  6835056691    服装      袜子   3.0    29     87
154  5854493676    服装     牛仔裤   2.0   399    798
155  6862563518    服装     西装裤   7.0   449   3143
156  6811607405    食品      饼干   6.0    39    234
157  6869448173    食品     巧克力   3.0    59    177
158  5848997046    图书     散文集   8.0    59    472
159  5811798968    服装      内衣   5.0    89    445
160  6821795644    食品      咖啡   8.0   129   1032
161  5864529489    图书    旅游指南   2.0    69    138
162  6855377041    图书      日历   5.0    39    195
163  5830456448  家居用品      窗帘   3.0   399   1197
164  6871381333  电子产品     路由器   4.0   299   1196
165  6888789224    服装      手套   7.0    59    413
166  5801646266    食品   零食大礼包   4.0    89    356
167  5874099485  家居用品      香薰   7.0    99    693
168  5843813257  家居用品      沙发   1.0  3999   3999
169  5843474151    服装     西装裤   1.0   449    449
170  5819162283  家居用品      窗帘   2.0   399    798
171  5879241383    图书     摄影集   5.0   129    645
172  6890353450    食品     方便面   5.0    49    245
173  6865052496    服装     半身裙   8.0   299   2392
174  6805321631    服装      外套   1.0   599    599
175  5805146346    食品      咖啡   5.0   129    645
176  6873127248  家居用品      地毯   8.0   299   2392
177  6844904388  家居用品     收纳盒  10.0    79    790
178  6836585103  电子产品  USB数据线   9.0    29    261
179  5821778573    服装      衬衫   7.0   299   2093
180  6805779311    服装     运动裤   8.0   249   1992
181  5801873309  电子产品     路由器   7.0   299   2093
182  6842433686  电子产品      U盘   1.0    59     59
183  5827508455  家居用品      蜡烛   5.0    49    245
184  6855956978  家居用品      蜡烛   2.0    49     98
185  6817708051  家居用品      蜡烛   5.0    49    245
186  5837602170    图书      字帖   8.0    29    232
187  6816376743  电子产品  USB数据线   2.0    29     58
188  5816285494    食品      牛奶   1.0    69     69
189  6878949527  电子产品    无线耳机   3.0   299    897
190  5867072555    服装     西装裤   2.0   449    898
191  5876638261    服装      袜子   5.0    29    145
192  5874746458    服装     西装裤   1.0   449    449
193  6859826757    图书      画册   2.0    99    198
194  6855967378    图书      字帖   6.0    29    174
195  6812374694    服装      毛衣   9.0   399   3591
196  5847458425  家居用品      桌布   9.0    79    711
197  6826667587    服装     连衣裙   5.0   499   2495
198  5823039491    图书     练习册   2.0    39     78
199  6844981163    食品      茶叶   2.0   199    398
200  6852976345  电子产品     手机壳   5.0    49    245
201  5814938951  电子产品    平板电脑  10.0  2499  24990
202  5828470938    服装      短裤   2.0   149    298
203  6835026769    图书      诗集   2.0    49     98
204  6890609921  电子产品   笔记本电脑  10.0  5999  59990
205  6869333277  家居用品      床垫   9.0  5999  53991
206  6873254331  家居用品      窗帘   1.0   399    399
207  5881589365  家居用品      枕头   1.0   199    199
208  5822667696    图书     摄影集   8.0   129   1032
209  5852286595  电子产品     手机壳   6.0    49    294
210  5868514156    食品      果干  10.0    59    590
211  6850815278  家居用品      枕头   6.0   199   1194
212  6824315481  家居用品      衣架   8.0    39    312
213  6845880542    食品      海苔  10.0    29    290
214  6811136677  电子产品     显示器   5.0  1299   6495
215  5811267840    服装      短裤   8.0   149   1192
216  6874679301    服装     休闲裤   5.0   299   1495
217  6825956707  家居用品      毛巾   5.0    49    245
218  6879211098    图书     练习册  10.0    39    390
219  6883194186    食品      肉脯  10.0    69    690
220  5853054830    食品      肉脯   1.0    69     69
221  5805170374  家居用品      水杯   8.0    49    392
222  5863073750    食品      海苔   6.0    29    174
223  6879242690    食品   零食大礼包   3.0    89    267
224  5891062479    食品      饼干  10.0    39    390
225  6872729357    服装      短裤   4.0   149    596
226  5889283753  电子产品    智能音箱   5.0   399   1995
227  5814567651  家居用品      毛巾   6.0    49    294
228  5885541001  家居用品    餐具套装   6.0   199   1194
229  6824310511  家居用品      枕头   6.0   199   1194
230  5878969657  家居用品      床垫   8.0  5999  47992
231  5853861556  电子产品     钢化膜   5.0    39    195
232  5827118463    食品      面包  10.0    29    290
233  5884726526  家居用品     收纳盒   1.0    79     79
234  6841626372  家居用品      沙发   2.0  3999   7998
235  6824834965    食品      坚果  10.0    79    790
236  5864200262  家居用品      床垫   4.0  5999  23996
237  6823999604    图书    旅游指南  10.0    69    690
238  6813380522  电子产品    智能手机   3.0  2999   8997
239  5854306954  家居用品      毛巾   6.0    49    294
240  5876354209    图书     笔记本   5.0    49    245
241  6804390223    食品      糖果   6.0    39    234
242  5825538313  电子产品     钢化膜   1.0    39     39
243  5887227925  电子产品    平板电脑   2.0  2499   4998
244  5893361218    图书     笔记本   3.0    49    147
245  5818152363  电子产品    蓝牙耳机   8.0   199   1592
246  6858035154    食品     方便面  10.0    49    490
247  6889194588    食品     巧克力   5.0    59    295
248  6833067503  家居用品      纸巾   5.0    39    195
249  6882063897    食品     巧克力   4.0    59    236
250  5814816711  家居用品      蜡烛   8.0    49    392
251  6815487266    图书    技术书籍   5.0    89    445
252  5841352622  家居用品      拖把   1.0    89     89
253  5841427707    食品      蜂蜜   7.0    89    623
254  5805792947  家居用品      扫把   4.0    39    156
255  6874166656    食品      麦片   2.0    49     98
256  6888548139    食品     能量棒   7.0    49    343
257  6867654283  电子产品    无线耳机   2.0   299    598
258  6837893528  家居用品      扫把   4.0    39    156
259  6890392173    食品      茶叶   5.0   199    995
260  6853663987    食品   零食大礼包   2.0    89    178
261  6802052554    服装      睡衣   3.0   199    597
262  5822424851    食品      坚果   4.0    79    316
263  6838941887  电子产品     路由器   7.0   299   2093
264  5851089960  家居用品      毛巾  10.0    49    490
265  5823329114    图书      字典   7.0    99    693
266  5821040515  电子产品     钢化膜   9.0    39    351
267  6830515225    图书     摄影集   7.0   129    903
268  6822412203    服装     休闲裤   8.0   299   2392
269  5817231648    服装      衬衫   5.0   299   1495
270  6841473447    食品      果汁   4.0    39    156
271  5815401663  家居用品      沙发   9.0  3999  35991
272  6832245129    食品     矿泉水  10.0    29    290
273  5884006836    食品      海苔   6.0    29    174
274  6808702911  电子产品     路由器   4.0   299   1196
275  5836984659    图书      食谱   7.0    49    343
276  5878122717  电子产品    智能手表  10.0   899   8990
277  6890876412    食品      海苔   1.0    29     29
278  6824270558    食品      薯片   1.0    19     19
279  6814064009    图书     练习册   9.0    39    351
280  5832052306  家居用品      毛巾   2.0    49     98
281  5865217126  电子产品     存储卡   7.0   129    903
282  6813149131  电子产品     手机壳   9.0    49    441
283  5865254576    食品     方便面   2.0    49     98
284  5864343049    服装      风衣   1.0   699    699
285  6824634614    服装     西装裤   2.0   449    898
286  5872729055  电子产品      键盘   2.0   199    398
287  6818532821    图书      漫画   8.0    39    312
288  6820986832    食品      肉脯   3.0    69    207
289  6899877847  家居用品      枕头  10.0   199   1990
290  6886260421  电子产品    移动电源   4.0   149    596
291  6860752624    图书      字帖   7.0    29    203
292  5877457110    食品      蜂蜜   2.0    89    178
293  5832560118    食品      薯片   7.0    19    133
294  5880846456    服装     西装裤   9.0   449   4041
295  5875231157    图书     笔记本   6.0    49    294
296  5873373109  家居用品     洗衣液   2.0    49     98
297  6871646723    图书      杂志   7.0    29    203
298  6829733993  家居用品      窗帘   7.0   399   2793
299  6889261873    图书     笔记本   8.0    49    392
300  6869253277    食品     方便面   1.0    49     49
301  6807376898  家居用品      香薰   7.0    99    693
302  6869886459    图书      教材   3.0    79    237
303  6806160339    食品   零食大礼包   3.0    89    267
304  6862175114    食品      面包   8.0    29    232
305  6827231926    图书      字典   4.0    99    396
306  5826822786  家居用品      地毯   2.0   299    598
307  6807847191    图书      漫画   8.0    39    312
308  5854096632    服装     牛仔裤   4.0   399   1596
309  6838020550  家居用品      地毯   5.0   299   1495
310  5838148763  电子产品    蓝牙耳机  10.0   199   1990
311  5855677494    食品      坚果  10.0    79    790
312  6812559570  电子产品    智能手表   9.0   899   8091
313  6833144246    食品     能量棒   5.0    49    245
314  6889158121    食品      牛奶  10.0    69    690
315  5881823286    图书      画册   5.0    99    495
316  6801495528    图书     历史书   9.0    89    801
317  6867566121    图书    旅游指南   6.0    69    414
318  6817604870    服装      围巾   5.0   129    645
319  6827897151    食品     能量棒   9.0    49    441
320  5830696359    食品      坚果   3.0    79    237
321  6840828332  家居用品     洗衣液   7.0    49    343
322  5857696039  电子产品    蓝牙耳机   8.0   199   1592
323  5859034879    服装     连衣裙   9.0   499   4491
324  5849308732    服装      风衣   5.0   699   3495
325  6809660384    食品     矿泉水   5.0    29    145
326  6803745732  家居用品     垃圾桶   8.0    59    472
327  5876386922    图书      漫画   6.0    39    234
328  5872884276    图书      食谱   5.0    49    245
329  6862898039    图书      字帖   9.0    29    261
330  6887906700  电子产品    移动电源   7.0   149   1043
331  5822235365  家居用品     垃圾桶   9.0    59    531
332  6836140342    食品   零食大礼包   1.0    89     89
333  6866915478    图书      绘本   2.0    59    118
334  5872942373    食品      饼干   8.0    39    312
335  6851028631    图书      字帖   1.0    29     29
336  6869653239    食品      糖果   6.0    39    234
337  5801962133  家居用品     收纳盒   2.0    79    158
338  6832952335    食品      果干   4.0    59    236
339  6840926430    图书     摄影集  10.0   129   1290
340  5834735575    食品      酸奶   5.0    59    295
341  6876402501    服装      睡衣  10.0   199   1990
342  6851411201    图书      字典   3.0    99    297
343  5825644770  家居用品     垃圾桶   2.0    59    118
344  6884360308  电子产品   笔记本电脑   5.0  5999  29995
345  6858821045  家居用品      沙发   8.0  3999  31992
346  6878999122  家居用品      香薰   3.0    99    297
347  5884742846    食品     巧克力   2.0    59    118
348  6873035797  电子产品     路由器   2.0   299    598
349  5871133274  电子产品      鼠标   1.0    89     89
350  5839574954  家居用品      地毯   4.0   299   1196
351  5878252086    食品      肉脯   7.0    69    483
352  6826816957    服装      手套   5.0    59    295
353  5881472337  家居用品      桌布   4.0    79    316
354  5831710697  家居用品    餐具套装   6.0   199   1194
355  6818372908    服装      风衣   1.0   699    699
356  6890163345    食品     矿泉水   9.0    29    261
357  5866711381    食品      肉脯  10.0    69    690
358  6874405722    食品      果汁   6.0    39    234
359  6862347895  电子产品      U盘  10.0    59    590
360  6862143082    图书     散文集  10.0    59    590
361  6881174739  家居用品      水杯   3.0    49    147
362  5890937948  电子产品  USB数据线   1.0    29     29
363  6859092130  家居用品      床垫   4.0  5999  23996
364  6864610136  电子产品    平板电脑   9.0  2499  22491
365  6856858615  电子产品    智能手机   5.0  2999  14995
366  6874044470    图书      字典   6.0    99    594
367  6811229309  家居用品      拖把   2.0    89    178
368  5867096000  电子产品    移动电源   3.0   149    447
369  5869692650  电子产品    移动电源   7.0   149   1043
370  5861400879    服装      卫衣   7.0   349   2443
371  5827294885  电子产品    移动电源   2.0   149    298
372  6878930826  电子产品  USB数据线   1.0    29     29
373  6894030876    图书      绘本   9.0    59    531
374  5866314665  电子产品     手机壳   9.0    49    441
375  5844313707    服装      短裤   3.0   149    447
376  5898273477  家居用品      毛巾   3.0    49    147
377  5878946554    服装      手套   6.0    59    354
378  5838636156    食品      蜂蜜   4.0    89    356
379  5852580673    食品      坚果   1.0    79     79
380  6891639233    食品      蜂蜜   6.0    89    534
381  6841710658  电子产品    无线耳机   9.0   299   2691
382  5844830398    食品      茶叶   9.0   199   1791
383  5813870384  电子产品    智能手表   3.0   899   2697
384  5800257671    图书    旅游指南   2.0    69    138
385  6868880875  家居用品      被子   9.0   399   3591
386  6835453724    图书     科普书   3.0    59    177
387  6837647011    服装      卫衣  10.0   349   3490
388  6873163407    图书     摄影集   7.0   129    903
389  5804112603  家居用品      沙发   2.0  3999   7998
390  6849785580  电子产品   笔记本电脑  10.0  5999  59990
391  5869835128  电子产品     手机壳   9.0    49    441
392  6802890262    图书      小说   9.0    49    441
393  5867475720    服装      卫衣   9.0   349   3141
394  5868828994    图书      字典   7.0    99    693
395  6898045661    图书     历史书   3.0    89    267
396  6865928279  电子产品     显示器   4.0  1299   5196
397  5831333751  电子产品    平板电脑   9.0  2499  22491
398  6845600235    食品     矿泉水   8.0    29    232
399  6860434598    图书      诗集   3.0    49    147
400  5863886364    服装      内衣   1.0    89     89
401  5803917597  家居用品      地毯   9.0   299   2691
402  6886426092    图书    技术书籍   7.0    89    623
403  6859888529    食品      咖啡   5.0   129    645
404  6895298343  电子产品    智能手机   9.0  2999  26991
405  6826516262  家居用品      蜡烛   6.0    49    294
406  6817711302  家居用品      枕头   6.0   199   1194
407  5813878248  电子产品     麦克风   9.0   299   2691

In [65]:
# 2.3异常值处理
# 2.3.1 查看异常值
data[data['单价'] < 0]

# 2.3.2 删除异常值
data.drop(data[data['单价'] < 0].index)

# 2.3.3 修复异常值
data.loc[data['单价'] < 0, '单价'] = 29
data.loc[data['销售金额'] < 0, '销售金额'] = 203
data

            订单号  产品类别    产品名称  销售数量    单价   销售金额
0    6805677496  家居用品      枕头  10.0   199   1990
1    5857234132    食品      海苔   5.0    29    145
2    5888085059  电子产品    智能音箱   NaN   399   1995
3    6823473137    食品      面包   3.0    29     87
4    6801664364    食品      薯片   2.0    19     38
5    5897064217    图书      字帖   4.0    29    116
6    6857752388    服装      袜子   7.0    29    203
7    6898807429    服装      T恤   6.0   199   1194
8    5875402232  电子产品     路由器   9.0   299   2691
9    5888085059    图书      字典   2.0    99    198
10   5808071569    食品     矿泉水   9.0    29    261
11   6890234923  家居用品    餐具套装  10.0   199   1990
12   5891597362  电子产品      鼠标   3.0    89    267
13   6880065056    图书     练习册   8.0    39    312
14   5804178086  电子产品    蓝牙耳机  10.0   199   1990
15   5878551159    图书     练习册   5.0    39    195
16   5812573980    食品      坚果   2.0    79    158
17   5835623429    图书      食谱   6.0    49    294
18   5852698441  家居用品      蜡烛   6.0    49    294
19   5852807025    服装      毛衣  10.0   399   3990
20   6893087111    食品      蜂蜜  10.0    89    890
21   5871374068    图书     摄影集   5.0   129    645
22   5894724625  电子产品    智能手机   9.0  2999  26991
23   6867258691    服装      围巾   8.0   129   1032
24   5875023454  电子产品    智能手机   8.0  2999  23992
25   6837065480    服装      毛衣   3.0   399   1197
26   5854211330    食品      果干   9.0    59    531
27   5840958148    服装      衬衫   6.0   299   1794
28   6842052369  家居用品      扫把   1.0    39     39
29   5816896128    食品      咖啡   4.0   129    516
30   6821256262    图书      食谱   6.0    49    294
31   5837205437    服装      短裤   2.0   149    298
32   6816687256    服装     运动裤   7.0   249   1743
33   6867240278    服装      短裤   8.0   149   1192
34   6859288203  电子产品     钢化膜   2.0    39     78
35   5815847468  电子产品     显示器   5.0  1299   6495
36   6870668206  家居用品      拖把   6.0    89    534
37   6871778377    食品      薯片   2.0    19     38
38   6896363474    图书     练习册   7.0    39    273
39   6857955578    图书     科普书   5.0    59    295
40   5864587553    服装      袜子   8.0    29    232
41   6861733608  家居用品      衣架   2.0    39     78
42   5848602769    食品     能量棒   1.0    49     49
43   6896687125    食品      果汁   2.0    39     78
44   5809051775  电子产品      鼠标   9.0    89    801
45   5828073333  家居用品      水杯   2.0    49     98
46   5820473594    服装     运动裤   7.0   249   1743
47   5823379341  电子产品   笔记本电脑   1.0  5999   5999
48   5835099410    图书    技术书籍   4.0    89    356
49   6842655345    食品      蜂蜜   7.0    89    623
50   6872501498  家居用品      衣架   4.0    39    156
51   6803742747  电子产品     麦克风   2.0   299    598
52   5835714436    服装      围巾   2.0   129    258
53   6807804795  电子产品     钢化膜   9.0    39    351
54   6872340030  家居用品      衣架   5.0    39    195
55   6840254213    食品     矿泉水  10.0    29    290
56   5870793859    食品      饼干   6.0    39    234
57   5876880041    服装     运动裤   2.0   249    498
58   6885078432  家居用品      沙发   7.0  3999  27993
59   5805524413    食品      牛奶   5.0    69    345
60   6802066319    服装      睡衣   4.0   199    796
61   5876009437    食品      肉脯   7.0    69    483
62   6857386517    食品      海苔   4.0    29    116
63   6893849823  电子产品      键盘   3.0   199    597
64   6818686763  家居用品    餐具套装   6.0   199   1194
65   6818771197    服装     羽绒服   4.0   899   3596
66   6803345146  电子产品    智能音箱  10.0   399   3990
67   6857671635  电子产品     手机壳   1.0    49     49
68   6888558142    服装      手套   5.0    59    295
69   5802859418  家居用品     洗衣液   2.0    49     98
70   5857892499    食品     巧克力   6.0    59    354
71   6881307037    服装      外套   6.0   599   3594
72   6882472708    食品   零食大礼包   5.0    89    445
73   6896836654  家居用品      窗帘   1.0   399    399
74   6807517971  电子产品    无线耳机   1.0   299    299
75   6868450800    图书      绘本   9.0    59    531
76   5835168341    服装      围巾   5.0   129    645
77   6862213600  电子产品     手机壳   9.0    49    441
78   5817942253  家居用品      毛巾   9.0    49    441
79   6838419156    服装      T恤   1.0   199    199
80   6832672046    服装      卫衣   2.0   349    698
81   6882641183    食品      坚果   1.0    79     79
82   5882040279    图书     练习册   3.0    39    117
83   5856960206    食品     能量棒   3.0    49    147
84   6835930946    服装     休闲裤   2.0   299    598
85   6884401422    图书     笔记本   9.0    49    441
86   6817646898  家居用品      衣架   8.0    39    312
87   5824138220    图书      日历   3.0    39    117
88   5810483850  家居用品      床垫   5.0  5999  29995
89   6874228092  电子产品    无线耳机   1.0   299    299
90   5825937662  电子产品     钢化膜   6.0    39    234
91   6899540878  家居用品      床垫   4.0  5999  23996
92   6815202927  家居用品      地毯   8.0   299   2392
93   5803850839  电子产品      键盘   6.0   199   1194
94   6850947020  家居用品      纸巾   5.0    39    195
95   5840069589    图书      画册   3.0    99    297
96   6882159173    食品      蜂蜜   7.0    89    623
97   6847661479    食品      薯片   8.0    19    152
98   5848428039    食品      茶叶  10.0   199   1990
99   6868231493    食品      薯片   5.0    19     95
100  5832758970    服装      风衣   8.0   699   5592
101  6899145716    图书      杂志   8.0    29    232
102  6893625569    服装      围巾   8.0   129   1032
103  5863393961  电子产品    游戏手柄   2.0   249    498
104  6827358966    图书      字典   6.0    99    594
105  5878543628  家居用品     洗洁精  10.0    29    290
106  5824298537    服装      卫衣   8.0   349   2792
107  6868959743    图书     笔记本   4.0    49    196
108  6826045080    服装      睡衣   3.0   199    597
109  5855176585    图书     科普书   5.0    59    295
110  6856521224    服装      风衣   6.0   699   4194
111  5838735887    图书      画册   7.0    99    693
112  5863809863  家居用品     垃圾桶   2.0    59    118
113  5818261249    食品      茶叶   6.0   199   1194
114  5845257567    图书      绘本   9.0    59    531
115  6876712100  家居用品      衣架   1.0    39     39
116  5854511595    食品   零食大礼包   2.0    89    178
117  5894610701  家居用品      拖把   2.0    89    178
118  6865301539    食品   零食大礼包   4.0    89    356
119  5862128107  家居用品      沙发   3.0  3999  11997
120  6885746519  电子产品    游戏手柄   4.0   249    996
121  6892321515    食品      坚果  10.0    79    790
122  5883797573    食品      麦片   7.0    49    343
123  5818113431  家居用品      床垫   8.0  5999  47992
124  6883278187  家居用品     垃圾桶   1.0    59     59
125  6818053882    食品      牛奶   4.0    69    276
126  5891955361  电子产品     钢化膜   5.0    39    195
127  5883983174  家居用品      窗帘  10.0   399   3990
128  5866054840    图书      字典  10.0    99    990
129  5821394002  家居用品     收纳盒   1.0    79     79
130  5839652877    图书      漫画   5.0    39    195
131  5866179578  电子产品   笔记本电脑   2.0  5999  11998
132  6860644623  电子产品     存储卡   1.0   129    129
133  5817207922    服装     连衣裙   7.0   499   3493
134  6826538206  电子产品     麦克风   7.0   299   2093
135  6861726538  家居用品      地毯  10.0   299   2990
136  6873808416  家居用品      沙发   8.0  3999  31992
137  5813233987    食品     方便面   5.0    49    245
138  5853556066  家居用品      纸巾   8.0    39    312
139  6879411860  家居用品      沙发   6.0  3999  23994
140  5831376701    食品      薯片   2.0    19     38
141  5879174422    图书     散文集   6.0    59    354
142  5823360689  电子产品    智能手机   7.0  2999  20993
143  5883051305  电子产品    智能手机  10.0  2999  29990
144  6832294234    食品      咖啡   2.0   129    258
145  6871931711  家居用品      衣架  10.0    39    390
146  6856378469    服装     半身裙   8.0   299   2392
147  5800194073    服装      毛衣   6.0   399   2394
148  5800449605  家居用品     洗洁精   8.0    29    232
149  5846265329  家居用品      床垫   3.0  5999  17997
150  5867938109  电子产品      键盘   2.0   199    398
151  5893341133    食品      糖果   7.0    39    273
152  6875304597    食品     能量棒   8.0    49    392
153  6835056691    服装      袜子   3.0    29     87
154  5854493676    服装     牛仔裤   2.0   399    798
155  6862563518    服装     西装裤   7.0   449   3143
156  6811607405    食品      饼干   6.0    39    234
157  6869448173    食品     巧克力   3.0    59    177
158  5848997046    图书     散文集   8.0    59    472
159  5811798968    服装      内衣   5.0    89    445
160  6821795644    食品      咖啡   8.0   129   1032
161  5864529489    图书    旅游指南   2.0    69    138
162  6855377041    图书      日历   5.0    39    195
163  5830456448  家居用品      窗帘   3.0   399   1197
164  6871381333  电子产品     路由器   4.0   299   1196
165  6888789224    服装      手套   7.0    59    413
166  5801646266    食品   零食大礼包   4.0    89    356
167  5874099485  家居用品      香薰   7.0    99    693
168  5843813257  家居用品      沙发   1.0  3999   3999
169  5843474151    服装     西装裤   1.0   449    449
170  5819162283  家居用品      窗帘   2.0   399    798
171  5879241383    图书     摄影集   5.0   129    645
172  6890353450    食品     方便面   5.0    49    245
173  6865052496    服装     半身裙   8.0   299   2392
174  6805321631    服装      外套   1.0   599    599
175  5805146346    食品      咖啡   5.0   129    645
176  6873127248  家居用品      地毯   8.0   299   2392
177  6844904388  家居用品     收纳盒  10.0    79    790
178  6836585103  电子产品  USB数据线   9.0    29    261
179  5821778573    服装      衬衫   7.0   299   2093
180  6805779311    服装     运动裤   8.0   249   1992
181  5801873309  电子产品     路由器   7.0   299   2093
182  6842433686  电子产品      U盘   1.0    59     59
183  5827508455  家居用品      蜡烛   5.0    49    245
184  6855956978  家居用品      蜡烛   2.0    49     98
185  6817708051  家居用品      蜡烛   5.0    49    245
186  5837602170    图书      字帖   8.0    29    232
187  6816376743  电子产品  USB数据线   2.0    29     58
188  5816285494    食品      牛奶   1.0    69     69
189  6878949527  电子产品    无线耳机   3.0   299    897
190  5867072555    服装     西装裤   2.0   449    898
191  5876638261    服装      袜子   5.0    29    145
192  5874746458    服装     西装裤   1.0   449    449
193  6859826757    图书      画册   2.0    99    198
194  6855967378    图书      字帖   6.0    29    174
195  6812374694    服装      毛衣   9.0   399   3591
196  5847458425  家居用品      桌布   9.0    79    711
197  6826667587    服装     连衣裙   5.0   499   2495
198  5823039491    图书     练习册   2.0    39     78
199  6844981163    食品      茶叶   2.0   199    398
200  6852976345  电子产品     手机壳   5.0    49    245
201  5814938951  电子产品    平板电脑  10.0  2499  24990
202  5828470938    服装      短裤   2.0   149    298
203  6835026769    图书      诗集   2.0    49     98
204  6890609921  电子产品   笔记本电脑  10.0  5999  59990
205  6869333277  家居用品      床垫   9.0  5999  53991
206  6873254331  家居用品      窗帘   1.0   399    399
207  5881589365  家居用品      枕头   1.0   199    199
208  5822667696    图书     摄影集   8.0   129   1032
209  5852286595  电子产品     手机壳   6.0    49    294
210  5868514156    食品      果干  10.0    59    590
211  6850815278  家居用品      枕头   6.0   199   1194
212  6824315481  家居用品      衣架   8.0    39    312
213  6845880542    食品      海苔  10.0    29    290
214  6811136677  电子产品     显示器   5.0  1299   6495
215  5811267840    服装      短裤   8.0   149   1192
216  6874679301    服装     休闲裤   5.0   299   1495
217  6825956707  家居用品      毛巾   5.0    49    245
218  6879211098    图书     练习册  10.0    39    390
219  6883194186    食品      肉脯  10.0    69    690
220  5853054830    食品      肉脯   1.0    69     69
221  5805170374  家居用品      水杯   8.0    49    392
222  5863073750    食品      海苔   6.0    29    174
223  6879242690    食品   零食大礼包   3.0    89    267
224  5891062479    食品      饼干  10.0    39    390
225  6872729357    服装      短裤   4.0   149    596
226  5889283753  电子产品    智能音箱   5.0   399   1995
227  5814567651  家居用品      毛巾   6.0    49    294
228  5885541001  家居用品    餐具套装   6.0   199   1194
229  6824310511  家居用品      枕头   6.0   199   1194
230  5878969657  家居用品      床垫   8.0  5999  47992
231  5853861556  电子产品     钢化膜   5.0    39    195
232  5827118463    食品      面包  10.0    29    290
233  5884726526  家居用品     收纳盒   1.0    79     79
234  6841626372  家居用品      沙发   2.0  3999   7998
235  6824834965    食品      坚果  10.0    79    790
236  5864200262  家居用品      床垫   4.0  5999  23996
237  6823999604    图书    旅游指南  10.0    69    690
238  6813380522  电子产品    智能手机   3.0  2999   8997
239  5854306954  家居用品      毛巾   6.0    49    294
240  5876354209    图书     笔记本   5.0    49    245
241  6804390223    食品      糖果   6.0    39    234
242  5825538313  电子产品     钢化膜   1.0    39     39
243  5887227925  电子产品    平板电脑   2.0  2499   4998
244  5893361218    图书     笔记本   3.0    49    147
245  5818152363  电子产品    蓝牙耳机   8.0   199   1592
246  6858035154    食品     方便面  10.0    49    490
247  6889194588    食品     巧克力   5.0    59    295
248  6833067503  家居用品      纸巾   5.0    39    195
249  6882063897    食品     巧克力   4.0    59    236
250  5814816711  家居用品      蜡烛   8.0    49    392
251  6815487266    图书    技术书籍   5.0    89    445
252  5841352622  家居用品      拖把   1.0    89     89
253  5841427707    食品      蜂蜜   7.0    89    623
254  5805792947  家居用品      扫把   4.0    39    156
255  6874166656    食品      麦片   2.0    49     98
256  6888548139    食品     能量棒   7.0    49    343
257  6867654283  电子产品    无线耳机   2.0   299    598
258  6837893528  家居用品      扫把   4.0    39    156
259  6890392173    食品      茶叶   5.0   199    995
260  6853663987    食品   零食大礼包   2.0    89    178
261  6802052554    服装      睡衣   3.0   199    597
262  5822424851    食品      坚果   4.0    79    316
263  6838941887  电子产品     路由器   7.0   299   2093
264  5851089960  家居用品      毛巾  10.0    49    490
265  5823329114    图书      字典   7.0    99    693
266  5821040515  电子产品     钢化膜   9.0    39    351
267  6830515225    图书     摄影集   7.0   129    903
268  6822412203    服装     休闲裤   8.0   299   2392
269  5817231648    服装      衬衫   5.0   299   1495
270  6841473447    食品      果汁   4.0    39    156
271  5815401663  家居用品      沙发   9.0  3999  35991
272  6832245129    食品     矿泉水  10.0    29    290
273  5884006836    食品      海苔   6.0    29    174
274  6808702911  电子产品     路由器   4.0   299   1196
275  5836984659    图书      食谱   7.0    49    343
276  5878122717  电子产品    智能手表  10.0   899   8990
277  6890876412    食品      海苔   1.0    29     29
278  6824270558    食品      薯片   1.0    19     19
279  6814064009    图书     练习册   9.0    39    351
280  5832052306  家居用品      毛巾   2.0    49     98
281  5865217126  电子产品     存储卡   7.0   129    903
282  6813149131  电子产品     手机壳   9.0    49    441
283  5865254576    食品     方便面   2.0    49     98
284  5864343049    服装      风衣   1.0   699    699
285  6824634614    服装     西装裤   2.0   449    898
286  5872729055  电子产品      键盘   2.0   199    398
287  6818532821    图书      漫画   8.0    39    312
288  6820986832    食品      肉脯   3.0    69    207
289  6899877847  家居用品      枕头  10.0   199   1990
290  6886260421  电子产品    移动电源   4.0   149    596
291  6860752624    图书      字帖   7.0    29    203
292  5877457110    食品      蜂蜜   2.0    89    178
293  5832560118    食品      薯片   7.0    19    133
294  5880846456    服装     西装裤   9.0   449   4041
295  5875231157    图书     笔记本   6.0    49    294
296  5873373109  家居用品     洗衣液   2.0    49     98
297  6871646723    图书      杂志   7.0    29    203
298  6829733993  家居用品      窗帘   7.0   399   2793
299  6889261873    图书     笔记本   8.0    49    392
300  6869253277    食品     方便面   1.0    49     49
301  6807376898  家居用品      香薰   7.0    99    693
302  6869886459    图书      教材   3.0    79    237
303  6806160339    食品   零食大礼包   3.0    89    267
304  6862175114    食品      面包   8.0    29    232
305  6827231926    图书      字典   4.0    99    396
306  5826822786  家居用品      地毯   2.0   299    598
307  6807847191    图书      漫画   8.0    39    312
308  5854096632    服装     牛仔裤   4.0   399   1596
309  6838020550  家居用品      地毯   5.0   299   1495
310  5838148763  电子产品    蓝牙耳机  10.0   199   1990
311  5855677494    食品      坚果  10.0    79    790
312  6812559570  电子产品    智能手表   9.0   899   8091
313  6833144246    食品     能量棒   5.0    49    245
314  6889158121    食品      牛奶  10.0    69    690
315  5881823286    图书      画册   5.0    99    495
316  6801495528    图书     历史书   9.0    89    801
317  6867566121    图书    旅游指南   6.0    69    414
318  6817604870    服装      围巾   5.0   129    645
319  6827897151    食品     能量棒   9.0    49    441
320  5830696359    食品      坚果   3.0    79    237
321  6840828332  家居用品     洗衣液   7.0    49    343
322  5857696039  电子产品    蓝牙耳机   8.0   199   1592
323  5859034879    服装     连衣裙   9.0   499   4491
324  5849308732    服装      风衣   5.0   699   3495
325  6809660384    食品     矿泉水   5.0    29    145
326  6803745732  家居用品     垃圾桶   8.0    59    472
327  5876386922    图书      漫画   6.0    39    234
328  5872884276    图书      食谱   5.0    49    245
329  6862898039    图书      字帖   9.0    29    261
330  6887906700  电子产品    移动电源   7.0   149   1043
331  5822235365  家居用品     垃圾桶   9.0    59    531
332  6836140342    食品   零食大礼包   1.0    89     89
333  6866915478    图书      绘本   2.0    59    118
334  5872942373    食品      饼干   8.0    39    312
335  6851028631    图书      字帖   1.0    29     29
336  6869653239    食品      糖果   6.0    39    234
337  5801962133  家居用品     收纳盒   2.0    79    158
338  6832952335    食品      果干   4.0    59    236
339  6840926430    图书     摄影集  10.0   129   1290
340  5834735575    食品      酸奶   5.0    59    295
341  6876402501    服装      睡衣  10.0   199   1990
342  6851411201    图书      字典   3.0    99    297
343  5825644770  家居用品     垃圾桶   2.0    59    118
344  6884360308  电子产品   笔记本电脑   5.0  5999  29995
345  6858821045  家居用品      沙发   8.0  3999  31992
346  6878999122  家居用品      香薰   3.0    99    297
347  5884742846    食品     巧克力   2.0    59    118
348  6873035797  电子产品     路由器   2.0   299    598
349  5871133274  电子产品      鼠标   1.0    89     89
350  5839574954  家居用品      地毯   4.0   299   1196
351  5878252086    食品      肉脯   7.0    69    483
352  6826816957    服装      手套   5.0    59    295
353  5881472337  家居用品      桌布   4.0    79    316
354  5831710697  家居用品    餐具套装   6.0   199   1194
355  6818372908    服装      风衣   1.0   699    699
356  6890163345    食品     矿泉水   9.0    29    261
357  5866711381    食品      肉脯  10.0    69    690
358  6874405722    食品      果汁   6.0    39    234
359  6862347895  电子产品      U盘  10.0    59    590
360  6862143082    图书     散文集  10.0    59    590
361  6881174739  家居用品      水杯   3.0    49    147
362  5890937948  电子产品  USB数据线   1.0    29     29
363  6859092130  家居用品      床垫   4.0  5999  23996
364  6864610136  电子产品    平板电脑   9.0  2499  22491
365  6856858615  电子产品    智能手机   5.0  2999  14995
366  6874044470    图书      字典   6.0    99    594
367  6811229309  家居用品      拖把   2.0    89    178
368  5867096000  电子产品    移动电源   3.0   149    447
369  5869692650  电子产品    移动电源   7.0   149   1043
370  5861400879    服装      卫衣   7.0   349   2443
371  5827294885  电子产品    移动电源   2.0   149    298
372  6878930826  电子产品  USB数据线   1.0    29     29
373  6894030876    图书      绘本   9.0    59    531
374  5866314665  电子产品     手机壳   9.0    49    441
375  5844313707    服装      短裤   3.0   149    447
376  5898273477  家居用品      毛巾   3.0    49    147
377  5878946554    服装      手套   6.0    59    354
378  5838636156    食品      蜂蜜   4.0    89    356
379  5852580673    食品      坚果   1.0    79     79
380  6891639233    食品      蜂蜜   6.0    89    534
381  6841710658  电子产品    无线耳机   9.0   299   2691
382  5844830398    食品      茶叶   9.0   199   1791
383  5813870384  电子产品    智能手表   3.0   899   2697
384  5800257671    图书    旅游指南   2.0    69    138
385  6868880875  家居用品      被子   9.0   399   3591
386  6835453724    图书     科普书   3.0    59    177
387  6837647011    服装      卫衣  10.0   349   3490
388  6873163407    图书     摄影集   7.0   129    903
389  5804112603  家居用品      沙发   2.0  3999   7998
390  6849785580  电子产品   笔记本电脑  10.0  5999  59990
391  5869835128  电子产品     手机壳   9.0    49    441
392  6802890262    图书      小说   9.0    49    441
393  5867475720    服装      卫衣   9.0   349   3141
394  5868828994    图书      字典   7.0    99    693
395  6898045661    图书     历史书   3.0    89    267
396  6865928279  电子产品     显示器   4.0  1299   5196
397  5831333751  电子产品    平板电脑   9.0  2499  22491
398  6845600235    食品     矿泉水   8.0    29    232
399  6860434598    图书      诗集   3.0    49    147
400  5863886364    服装      内衣   1.0    89     89
401  5803917597  家居用品      地毯   9.0   299   2691
402  6886426092    图书    技术书籍   7.0    89    623
403  6859888529    食品      咖啡   5.0   129    645
404  6895298343  电子产品    智能手机   9.0  2999  26991
405  6826516262  家居用品      蜡烛   6.0    49    294
406  6817711302  家居用品      枕头   6.0   199   1194

In [ ]:
# 数据格式转换