In [2]:
import pandas as pd

# 1.读取数据
data = pd.read_csv('data/sales.csv', nrows=10)
data

          订单号  产品类别  产品名称  销售数量   单价  销售金额
0  6805677496  家居用品    枕头  10.0  199  1990
1  5857234132    食品    海苔   5.0   29   145
2  5888085059  电子产品  智能音箱   NaN  399  1995
3  6823473137    食品    面包   3.0   29    87
4  6801664364    食品    薯片   2.0   19    38
5  5897064217    图书    字帖   4.0   29   116
6  6857752388    服装    袜子   7.0  -29  -203
7  6898807429    服装    T恤   6.0  199  1194
8  5875402232  电子产品   路由器   9.0  299  2691
9  5888085059    图书    字典   2.0   99   198

In [8]:
# 排序
# 2.1 根据销售数量 倒序排序
data.sort_values(by='销售数量', ascending=False)

# 2.2 根据单价 升序排序
data.sort_values(by='单价', ascending=True)

# 2.3 根据价格 升序排序，价格一样，再根据 销售数量 倒序排序
data.sort_values(by=['单价', '销售数量'], ascending=[True, False])

          订单号  产品类别  产品名称  销售数量   单价  销售金额
6  6857752388    服装    袜子   7.0  -29  -203
4  6801664364    食品    薯片   2.0   19    38
1  5857234132    食品    海苔   5.0   29   145
5  5897064217    图书    字帖   4.0   29   116
3  6823473137    食品    面包   3.0   29    87
9  5888085059    图书    字典   2.0   99   198
0  6805677496  家居用品    枕头  10.0  199  1990
7  6898807429    服装    T恤   6.0  199  1194
8  5875402232  电子产品   路由器   9.0  299  2691
2  5888085059  电子产品  智能音箱   NaN  399  1995

In [26]:
data = pd.read_csv("data/sales.csv", nrows = 20)

data['销售金额'] = data['单价'] * data['销售数量']
data
#3. 分组
# 3.1 根据 产品类别 分组，统计各个类别的 订单数量
data.groupby('产品类别')['订单号'].count()  #注意：缺失值不参与统计

# 3.2 根据 产品类别 分组，统计各个类别的 销售数量 之和
data.groupby('产品类别')['销售数量'].sum()

# 3.3 根据 产品类别 分组，统计各个类别的 销售金额 之和

data.groupby('产品类别')['销售金额'].sum()

# 3.4 根据 产品类别 分组，统计各个类别的最低商品 单价
data.groupby('产品类别')['单价'].min()

# 3.5 根据 产品类别 分组，统计各个类别的最高商品 单价
data.groupby('产品类别')['单价'].max()

# 3.6 根据 产品类别 分组，统计各个类别的平均商品 单价
data.groupby('产品类别')['单价'].mean()

# 3.7 根据 产品类别 分组，统计各个类别的商品的 平均单价、最高单价、最低单价
data.groupby('产品类别')['单价'].agg(['mean', 'max', 'min'])

# 3.8 根据 产品类别 分组，统计各个类别的商品的 销售数量 之和，销售金额 之和，平均 单价
data.groupby('产品类别').agg({'销售数量': 'sum', '销售金额': 'sum', '单价': 'mean'})

      销售数量    销售金额          单价
产品类别
图书    25.0  1115.0   51.000000
家居用品  26.0  4274.0  149.000000
服装    23.0  4981.0  189.666667
电子产品  22.0  4948.0  246.500000
食品    21.0   689.0   37.000000